FROM cwpearson/opencl2.0-intel-cpu:latest
RUN apt-get update && apt-get install -y cmake build-essential libeigen3-dev \
lsb-release libboost-all-dev libglu1-mesa-dev mesa-common-dev && apt-get clean all
RUN apt-get install -y pip3
